### ISSUE TITLE
Doesn't work with the game we want to translate

### ISSUE THREAD

**Issue by reiharus** [begerard/KagEditor#2]
Hello! 

We would like to implement this tool for our game so we can extract the script and localize it, it doesn't seem to work with our .ks files at the moment. Is there any chance you could contact me on my email address (it's on my profile) to talk about the details? @begerard I can't say much in public yet.

Thanks for making tools like this!

**Comment by begerard** [comment]
Hi,

Can you provide me a sample of file which doesn't work?

If you can't, as it's probably just a tag I haven't encounter yet, you can give me the lines that keep the tags in the cleaned file, or that doesn't reinsert them in the rescripted one.

**Comment by anabeled** [comment]
Hi, thanks for getting back

This is a sample .ks file from the game. The tool loads the files but doesn't seem to do anything. If I try exporting in unicode I get corrupted text.
https://drive.google.com/file/d/14A8mm1rRh50pyGQPPI1K2aYKaicWOVQa/view?usp=sharing

**Comment by begerard** [comment]
This file use the japanese only text encoding, so you have to set "**Japanese**" in "Open With" and keep "**Unicode**" in "Save With" to convert the file in international format. You can convert all the files of a directory (and subdirectories) with the "Clean All" command in Directory category.

For at least this file, the editor won't do anything else as there is no tags in the sentences, you only have commands between [] which does not really impede translation so I ignore them. You can directly translate the sentences (and leave the commands alone) and package it back in the game, it should works like that.

With Japanese encoded files the game probably don't works well on a non-japanese Windows, but usually if you re-encode all the file as Unicode (including configuration & script files), KAG games run fine on non-japanese Windows FYI.
